---

- name: Configure the Apache HTTP server for GitLab
  template: src=etc_apache2_sites-available_gitlab.conf.j2 dest=/etc/apache2/sites-available/gitlab.conf group=www-data owner=www-data
  notify: restart apache

- name: Enable the owncloud site
  command: a2ensite gitlab creates=/etc/apache2/sites-enabled/gitlab
  notify: restart apache
