# GitLab user. {{ gitlab_user }} by default
user: {{ gitlab_user }}

# Url to gitlab instance. Used for api calls. Should be ends with slash.
gitlab_url: "https://{{ gitlab_hostname if gitlab_hostname or ansible_hostname }}/"

http_settings:
#  user: someone
#  password: somepass
  self_signed_cert: false

# Repositories path
repos_path: "/decrypted/repositories"

# File used as authorized_keys for gitlab user
auth_file: "/var/www/gitlab/.ssh/authorized_keys"

# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: 127.0.0.1
  port: 6379
  # socket: /tmp/redis.socket # Only define this if you want to use sockets
  namespace: resque:gitlab

# Log file.
# Default is gitlab-shell.log in the root directory.
log_file: "/var/www/gitlab/log/gitlab-shell.log"

